import { OBSERVABLE_LABELS, SEVERITY_RANK, STATUS_LABELS, type FactValue, type InvestigationRecord } from "@/lib/core/types";
import { defang } from "@/lib/observables/fang";

export type ProviderNames = Record<string, string>;

function csvCell(value: unknown): string {
  const s = value === null || value === undefined ? "" : String(value);
  const safe = /^[=+\-@\t\r]/.test(s) ? `'${s}` : s;
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}

export function findingsCsv(inv: InvestigationRecord, names: ProviderNames): string {
  const rows = [["severity", "title", "rule", "category", "source", "observed_at", "affected_observable", "evidence", "description", "rationale", "remediation", "confidence"]];
  for (const f of [...inv.findings].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity])) {
    rows.push([f.severity, f.title, f.rule, f.category, names[f.source] ?? f.source, f.observedAt, f.observable ?? inv.normalizedObservable, f.evidence, f.description, f.rationale ?? "", f.remediation ?? "", f.confidence ?? ""]);
  }
  return rows.map((r) => r.map(csvCell).join(",")).join("\n") + "\n";
}

function factText(v: FactValue): string {
  if (Array.isArray(v)) return v.join(", ");
  if (typeof v === "boolean") return v ? "yes" : "no";
  return v === null ? "—" : String(v);
}

/** Markdown report. Observables are defanged so the report can be pasted safely into tickets and chat. */
export function reportMarkdown(inv: InvestigationRecord, names: ProviderNames): string {
  const L: string[] = [];
  const obs = defang(inv.normalizedObservable);
  L.push(`# Investigation report: ${obs}`, "");
  L.push(`| | |`, `|---|---|`);
  L.push(`| Observable | \`${obs}\` (${OBSERVABLE_LABELS[inv.observableType]}) |`);
  L.push(`| Mode | ${inv.mode === "DEEP" ? "Deep investigation" : "Quick scan"} |`);
  L.push(`| Status | ${inv.status} |`);
  L.push(`| Started | ${inv.createdAt} |`);
  if (inv.completedAt) L.push(`| Completed | ${inv.completedAt} (${Math.round((inv.durationMs ?? 0) / 100) / 10}s) |`);
  L.push(`| Report ID | ${inv.id} |`, "");
  L.push(`## Summary`, "", inv.summary || "—", "");

  L.push(`## Findings (${inv.findings.length})`, "");
  if (!inv.findings.length) L.push("No findings were produced.", "");
  for (const f of [...inv.findings].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity])) {
    L.push(`### [${f.severity}] ${f.title}`, "");
    L.push(f.description, "");
    if (f.rationale) L.push(`**Why it matters.** ${f.rationale}`, "");
    L.push(`**Evidence.** ${defang(f.evidence)}`, "");
    if (f.remediation) L.push(`**Remediation.** ${f.remediation}`, "");
    L.push(`Source: ${names[f.source] ?? f.source} · rule \`${f.rule}\` · observed ${f.observedAt}${f.confidence ? ` · confidence: ${f.confidence}` : ""}`, "");
    for (const r of f.references ?? []) L.push(`- [${r.label}](${r.url})`);
    if (f.references?.length) L.push("");
  }

  L.push(`## Sources`, "", `| Source | Status | Latency | Retrieved | Summary |`, `|---|---|---|---|---|`);
  for (const o of inv.providerResults) {
    const summary = o.result?.summary ?? o.errorMessage ?? "";
    L.push(`| ${names[o.provider] ?? o.provider} | ${STATUS_LABELS[o.status]}${o.cached ? " (cached)" : ""} | ${o.latencyMs} ms | ${o.retrievedAt} | ${defang(summary).replace(/\|/g, "\\|")} |`);
  }
  L.push("");

  for (const o of inv.providerResults.filter((x) => x.result?.facts.length)) {
    L.push(`### ${names[o.provider] ?? o.provider}`, "");
    for (const f of o.result!.facts) L.push(`- **${f.label}:** ${defang(factText(f.value))}`);
    L.push("");
  }

  if (inv.relationships.length) {
    L.push(`## Relationships (${inv.relationships.length})`, "");
    for (const r of inv.relationships.slice(0, 200)) L.push(`- ${defang(r.source.value)} —${r.type}→ ${defang(r.target.value)}${r.target.label ? ` (${r.target.label})` : ""} · ${r.providers.map((p) => names[p] ?? p).join(", ")}`);
    L.push("");
  }
  L.push("---", "Generated by NOPS / Cyber Intelligence. Findings are evidence-based; absence of findings is not proof of safety.");
  return L.join("\n");
}
