// Security encyclopedia content. Every article is hand-authored reference
// material — no data here comes from a live provider, so nothing is dated
// or attributed to a source that could go stale silently. References cite
// public standards (RFCs, CWE/CVE/CVSS, MITRE ATT&CK, OWASP) by identifier
// only, not by URL, since this module never fetches anything.

export type ArticleCategory = "web" | "network" | "malware" | "identity" | "cloud" | "detection" | "crypto";

export const CATEGORY_LABEL: Record<ArticleCategory, string> = {
  web: "Web & application",
  network: "Network",
  malware: "Malware",
  identity: "Identity & access",
  cloud: "Cloud & infrastructure",
  detection: "Detection & response",
  crypto: "Cryptography",
};

export interface Reference {
  label: string;
  note?: string;
}

export interface Article {
  slug: string;
  title: string;
  category: ArticleCategory;
  summary: string;
  what: string;
  why: string;
  how: string;
  detection: string;
  defence: string;
  related: string[];
  references: Reference[];
}

export const ARTICLES: Article[] = [
  {
    slug: "sql-injection",
    title: "SQL injection",
    category: "web",
    summary: "Untrusted input is concatenated into a database query, letting an attacker alter its logic.",
    what: "SQL injection (SQLi) happens when user-controlled input is inserted into a SQL statement without proper parameterization or escaping, allowing the attacker to change the query's structure rather than just its data.",
    why: "A successful injection can bypass authentication, read or modify arbitrary rows, enumerate schema, and on some database engines execute OS commands via stored procedures — making it one of the highest-impact classes of web vulnerability.",
    how: "Classic technique: terminate the intended string literal with a quote, then append boolean logic (' OR '1'='1) or a comment marker (--) to neutralise the rest of the query. Blind SQLi infers data one bit at a time from boolean or timing differences (e.g. SLEEP()) when no output is directly visible. Second-order SQLi stores a payload safely, then triggers it later when a different, unsafe query reads it back.",
    detection: "Static analysis for string-concatenated queries; WAF signatures for common injection tokens (though these are trivially bypassed); database audit logs showing malformed or anomalous query shapes; runtime instrumentation (RASP) that flags queries whose structure changes based on input.",
    defence: "Parameterized queries / prepared statements as the default, never string concatenation; an ORM used correctly; least-privilege database accounts per service; input validation as defense in depth, not a substitute for parameterization; disable verbose DB error messages in production.",
    related: ["command-injection", "path-traversal", "idor", "insecure-deserialization"],
    references: [{ label: "CWE-89: SQL Injection" }, { label: "OWASP Top 10 A03:2021 — Injection" }],
  },
  {
    slug: "cross-site-scripting",
    title: "Cross-site scripting (XSS)",
    category: "web",
    summary: "Unsanitized user input is rendered as executable HTML/JS in another user's browser session.",
    what: "XSS lets an attacker inject client-side script that runs in the context of a victim's authenticated session. Reflected XSS bounces a payload straight back in a response; stored XSS persists it (e.g. in a comment) for later victims; DOM-based XSS never touches the server — a client-side script itself writes attacker-controlled data into a dangerous DOM sink.",
    why: "Script running as the victim can read cookies and localStorage, perform actions as the victim (CSRF-equivalent), rewrite the page, harvest credentials via a fake login prompt, or pivot into further attacks — all without needing to compromise the server.",
    how: "The attacker finds a place where input is reflected or stored without HTML-encoding and inserts a vector — a <script> tag, an event handler such as onerror on a broken <img>, or a javascript: URL — that the browser then executes as part of the page.",
    detection: "Content-Security-Policy violation reports; output-encoding linters in CI; DAST scanners that fire canary payloads and check whether they execute; anomalous outbound requests from user sessions (data exfiltration).",
    defence: "Context-aware output encoding (HTML, attribute, JS, URL contexts each need different encoding) applied at render time, not just on input; a strict, nonce- or hash-based Content-Security-Policy with no unsafe-inline; frameworks that auto-escape by default (React, Vue) used without bypassing their escaping (dangerouslySetInnerHTML, v-html); HttpOnly and SameSite cookies to limit what a successful XSS can steal.",
    related: ["csrf", "ssrf", "insecure-deserialization"],
    references: [{ label: "CWE-79: Improper Neutralization of Input During Web Page Generation" }, { label: "OWASP Top 10 A03:2021 — Injection" }],
  },
  {
    slug: "csrf",
    title: "Cross-site request forgery (CSRF)",
    category: "web",
    summary: "A victim's browser is tricked into sending an authenticated request the victim never intended.",
    what: "CSRF abuses the fact that browsers automatically attach cookies to any request to a site, including ones triggered by a different, attacker-controlled page. A hidden form or image tag on the attacker's page submits a state-changing request to the target site using the victim's existing session.",
    why: "Because the request rides on the victim's real, authenticated session, the target application cannot distinguish it from a legitimate action — enabling unauthorized fund transfers, password/email changes, or privilege grants performed silently in the background.",
    how: "The attacker builds a page containing an auto-submitting form (or a simple GET via an <img> tag for state-changing GET endpoints, which is itself a bug) pointed at a sensitive endpoint on the target site, then lures the logged-in victim to visit it.",
    detection: "Server-side logs showing state-changing requests with a Referer/Origin header from an unexpected domain; missing or invalid anti-CSRF tokens on write requests; SameSite cookie rejection events.",
    defence: "Anti-CSRF tokens tied to the session and validated server-side on every state-changing request; SameSite=Lax or Strict cookies as a strong default mitigation; checking the Origin/Referer header; never using GET for state-changing operations.",
    related: ["cross-site-scripting", "ssrf"],
    references: [{ label: "CWE-352: Cross-Site Request Forgery" }, { label: "OWASP Top 10 A01:2021 — Broken Access Control" }],
  },
  {
    slug: "ssrf",
    title: "Server-side request forgery (SSRF)",
    category: "web",
    summary: "A server is tricked into making a request to a destination the attacker chose, not the operator.",
    what: "SSRF occurs when an application takes a user-supplied URL or hostname and fetches it server-side — e.g. for a webhook, an image proxy, or a PDF renderer — without adequately restricting the destination, letting the attacker redirect that server-side request to internal infrastructure.",
    why: "Cloud metadata endpoints (169.254.169.254), internal admin panels, databases, and other services that are unreachable from the internet are often fully trusted on an internal network — SSRF turns the vulnerable server into a proxy that reaches them, frequently yielding cloud credentials or full internal reconnaissance.",
    how: "Direct: supply an internal IP or a metadata-service URL where a URL parameter is expected. Bypass-oriented: use DNS rebinding, alternate IP encodings (decimal/octal/IPv6-mapped), open redirects, or a delay between validation and use (TOCTOU) to slip past an allowlist check.",
    detection: "Outbound connection logs from application servers to RFC 1918 / link-local ranges; anomalous DNS resolutions for a hostname immediately followed by a very different resolution (rebinding); WAF/EDR alerts on requests to the cloud metadata IP.",
    defence: "Resolve and validate the destination IP at connection time, not just the input string (blocks TOCTOU and DNS rebinding); enforce an allowlist of destinations rather than a denylist; disable unused URL schemes and following of redirects, or re-validate after each redirect; run outbound-fetching services with no route to internal-only networks; require IMDSv2 (token-bound) on cloud instances.",
    related: ["cross-site-scripting", "csrf", "cloud-misconfiguration"],
    references: [{ label: "CWE-918: Server-Side Request Forgery" }, { label: "OWASP Top 10 A10:2021 — Server-Side Request Forgery" }],
  },
  {
    slug: "xxe",
    title: "XML external entity (XXE) injection",
    category: "web",
    summary: "A misconfigured XML parser resolves attacker-defined external entities during parsing.",
    what: "XML allows a DOCTYPE to declare custom entities, including ones that reference an external URI. If a parser processes untrusted XML with external entity resolution enabled, an attacker-declared entity can pull in local file contents or make outbound requests as part of parsing an otherwise ordinary-looking document.",
    why: "XXE can disclose arbitrary local files (including credentials and keys), perform SSRF against internal services, and in some parser configurations (billion laughs / entity expansion) cause denial of service through exponential memory growth.",
    how: "The attacker submits XML containing a DOCTYPE with an external entity, e.g. one pointing at file:///etc/passwd or an internal URL, then references that entity inside an element whose value is reflected back in the response.",
    detection: "Outbound requests or file-read attempts originating from an XML-parsing code path; parser library CVE alerts; WAF rules flagging DOCTYPE/ENTITY declarations in XML uploads.",
    defence: "Disable DTD processing and external entity resolution in the XML parser by default — nearly every modern XML library supports this as a configuration flag; prefer a data format that has no entity concept (JSON) where XML isn't required; validate uploaded XML against a strict schema.",
    related: ["ssrf", "insecure-deserialization"],
    references: [{ label: "CWE-611: Improper Restriction of XML External Entity Reference" }, { label: "OWASP Top 10 A05:2021 — Security Misconfiguration" }],
  },
  {
    slug: "command-injection",
    title: "OS command injection",
    category: "web",
    summary: "User input reaches a shell command line, letting an attacker chain arbitrary commands.",
    what: "Command injection occurs when an application builds a shell command string by concatenating user input, so shell metacharacters (;, &&, |, `, $()) in that input let the attacker terminate the intended command and run their own.",
    why: "A successful injection runs with whatever privileges the vulnerable process has — often enough to read sensitive files, establish persistence, or pivot further into the host and network.",
    how: "The attacker appends a metacharacter and a second command to an input field that the application passes unsanitized to a shell — for example a hostname field for a diagnostic 'ping' feature becomes 'example.com; cat /etc/passwd'.",
    detection: "EDR/process-monitoring alerts on a web server process spawning an unexpected child shell; anomalous argv patterns in audit logs (auditd/Sysmon Event ID 1); WAF signatures for shell metacharacters in request parameters.",
    defence: "Avoid invoking a shell at all — call the target binary directly with an argv array (execve-style), which makes metacharacters inert; if a shell is unavoidable, use the platform's proper quoting/escaping API rather than hand-rolled escaping; validate input against a strict allowlist (e.g. a hostname regex) before it is ever used.",
    related: ["sql-injection", "path-traversal"],
    references: [{ label: "CWE-78: OS Command Injection" }, { label: "OWASP Top 10 A03:2021 — Injection" }],
  },
  {
    slug: "path-traversal",
    title: "Path traversal",
    category: "web",
    summary: "Unvalidated file paths let an attacker escape an intended directory using '../' segments.",
    what: "Path (or directory) traversal occurs when an application builds a filesystem path from user input without normalizing and validating it, so '..' segments let the attacker reference files outside the directory the application intended to expose.",
    why: "Successful traversal typically discloses configuration files, source code, credentials, or SSH keys, and in a write path (upload/export) can let an attacker overwrite files outside the intended directory, including ones that lead to code execution.",
    how: "The attacker supplies a filename such as '../../../etc/passwd' (or an OS-specific / URL-encoded / null-byte variant) where the application expects a simple filename inside a fixed directory.",
    detection: "Web server or application logs showing '../' or its encoded forms in file-related parameters; file-integrity monitoring on sensitive paths; WAF rules for traversal sequences.",
    defence: "Resolve the path to a canonical absolute form and verify it is still inside the intended root directory before using it — never trust the string form alone; map user-supplied identifiers to files via a lookup table or ID rather than passing a path fragment through; run the process with filesystem permissions scoped to only what it needs.",
    related: ["command-injection", "idor"],
    references: [{ label: "CWE-22: Path Traversal" }],
  },
  {
    slug: "insecure-deserialization",
    title: "Insecure deserialization",
    category: "web",
    summary: "A serialized object from an untrusted source is reconstructed and trusted without verification.",
    what: "Many languages let objects be serialized to a byte stream and later reconstructed. If that stream comes from the client and the deserializer trusts it — reconstructing arbitrary types, running constructors/finalizers, or restoring fields like a role or permission flag — the attacker can manipulate application state or, in the worst case, achieve remote code execution via a deserialization gadget chain.",
    why: "Because deserialization can rebuild rich object graphs, a single insecure deserialization point can be far more powerful than an ordinary injection bug — some language runtimes have documented gadget chains that lead straight to code execution from deserializing untrusted bytes alone.",
    how: "The lightweight version: a client-editable field (like a JSON 'role') is trusted wholesale on deserialization, letting a user grant themselves elevated privileges. The severe version: crafted binary/serialized payloads (Java, .NET, PHP, Python pickle) trigger gadget chains during reconstruction that execute attacker code.",
    detection: "Unexpected object types or fields appearing in application state; crash or exception patterns consistent with a gadget-chain probe; outbound connections or process spawns immediately following a deserialization call.",
    defence: "Never deserialize untrusted data with a format that can reconstruct arbitrary types (Java native serialization, Python pickle, PHP unserialize); prefer schema-validated data formats (JSON/Protobuf) with explicit allow-listed fields; re-derive sensitive fields like roles from a trusted source rather than trusting them from the deserialized payload; keep deserialization libraries patched, since most exploitation relies on gadget classes present in specific library versions.",
    related: ["sql-injection", "idor", "xxe"],
    references: [{ label: "CWE-502: Deserialization of Untrusted Data" }, { label: "OWASP Top 10 A08:2021 — Software and Data Integrity Failures" }],
  },
  {
    slug: "idor",
    title: "Insecure direct object reference (IDOR)",
    category: "web",
    summary: "An application returns a resource by ID without checking that the caller actually owns it.",
    what: "IDOR is a broken-access-control bug where an endpoint accepts an object identifier (e.g. /invoices/1002) and returns or modifies that object based on identity alone, without verifying the authenticated caller is authorized to access that specific object.",
    why: "IDOR is trivial to exploit — often just incrementing a number — and can expose or modify every other user's data at scale, since it requires no injection or memory-corruption skill, only enumeration.",
    how: "The attacker authenticates normally, then changes the ID in a request they're otherwise authorized to make (their own invoice, order, or profile) to another user's ID and observes whether the response still succeeds.",
    detection: "Authorization-failure logging showing a spike in 403/404s from ID enumeration; anomaly detection on access patterns (a user's session touching many sequential IDs); API gateway rate-limiting on ID-based endpoints.",
    defence: "Enforce ownership/authorization checks server-side on every object access, independent of the object ID supplied — never rely on an ID being 'hard to guess' as a security control; prefer non-sequential, non-guessable identifiers (UUIDs) as defense in depth, not a substitute for the access check; centralize authorization logic so it can't be forgotten on a new endpoint.",
    related: ["path-traversal", "sql-injection"],
    references: [{ label: "CWE-639: Authorization Bypass Through User-Controlled Key" }, { label: "OWASP Top 10 A01:2021 — Broken Access Control" }],
  },
  {
    slug: "dns-spoofing",
    title: "DNS spoofing / cache poisoning",
    category: "network",
    summary: "Forged DNS responses redirect a victim's name resolution to an attacker-chosen address.",
    what: "DNS spoofing injects a forged response into a DNS resolution — either directly to a victim on the local network (ARP spoofing plus a rogue DNS reply) or into a recursive resolver's cache (cache poisoning), so subsequent lookups for a domain return an attacker-controlled IP.",
    why: "Once name resolution is compromised, everything the victim believes is 'the real site' — including a TLS-terminating proxy the attacker controls — can be silently substituted, enabling credential theft, malware delivery, or traffic interception.",
    how: "On-path spoofing: race a forged UDP response to arrive before the legitimate DNS server's answer, guessing (or knowing, if on the same network segment) the query ID. Cache poisoning: exploit weak source-port/query-ID randomization on a recursive resolver to inject a forged record that gets cached and served to other clients.",
    detection: "DNSSEC validation failures; unexpected TTL or answer changes for a stable domain; multiple DNS responses arriving for a single query (a sign of a race); monitoring for known-poisoned resolvers via passive DNS anomalies.",
    defence: "DNSSEC to cryptographically sign zone data so forged responses fail validation; DNS-over-TLS/HTTPS to prevent on-path tampering and eavesdropping; query ID and source port randomization on resolvers; for critical services, certificate pinning so a spoofed IP still fails TLS validation.",
    related: ["arp-spoofing", "man-in-the-middle"],
    references: [{ label: "RFC 4033–4035: DNSSEC" }, { label: "CWE-350: Reliance on Reverse DNS Resolution for a Security-Critical Action" }],
  },
  {
    slug: "arp-spoofing",
    title: "ARP spoofing",
    category: "network",
    summary: "Forged ARP replies make a victim's traffic route through the attacker on the local network.",
    what: "ARP has no authentication: any host on a local segment can broadcast an unsolicited reply claiming a given IP maps to its own MAC address. ARP spoofing exploits this to make a victim (and often the gateway) update their ARP cache to point at the attacker, routing traffic through the attacker's machine.",
    why: "This is the classic precondition for a local man-in-the-middle position — once traffic flows through the attacker, they can passively sniff unencrypted protocols, selectively drop packets, or actively tamper with responses (including injecting fake DNS answers).",
    how: "The attacker sends unsolicited ARP replies to the victim (claiming to be the gateway) and to the gateway (claiming to be the victim), then enables IP forwarding on their own machine so traffic continues to flow while being interceptable.",
    detection: "ARP watch tools flagging a MAC address suddenly claiming multiple IPs, or an IP's MAC changing without a corresponding DHCP event; switch port security / dynamic ARP inspection logs; unexpected duplicate ARP replies on the segment.",
    defence: "Dynamic ARP Inspection (DAI) and DHCP snooping on managed switches; static ARP entries for critical infrastructure (gateway, DNS server) where feasible; network segmentation to shrink the broadcast domain an attacker could be present on; end-to-end encryption (TLS) so an on-path position yields ciphertext, not usable data.",
    related: ["dns-spoofing", "man-in-the-middle"],
    references: [{ label: "RFC 826: Address Resolution Protocol" }, { label: "CWE-290: Authentication Bypass by Spoofing" }],
  },
  {
    slug: "man-in-the-middle",
    title: "Man-in-the-middle (MITM)",
    category: "network",
    summary: "An attacker positions themselves between two parties, relaying and optionally altering traffic.",
    what: "A MITM attack is any technique that gives an attacker an interception point between a client and server — via ARP/DNS spoofing on a LAN, a rogue Wi-Fi access point, a compromised router, or a malicious/misissued TLS certificate — so traffic that both parties believe is direct actually flows through the attacker.",
    why: "Positioning alone doesn't guarantee data access if the channel is properly encrypted and authenticated, but a successful MITM against a weak or misconfigured TLS setup (self-signed certs accepted without warning, certificate validation disabled, weak cipher downgrade) can fully expose or tamper with the traffic.",
    how: "Achieve position via ARP/DNS spoofing, a rogue access point with a familiar SSID, or router compromise; then either relay traffic transparently while logging it, or actively strip/downgrade TLS (SSL stripping) and present the attacker's own certificate to a client that doesn't validate strictly.",
    detection: "Certificate transparency log monitoring for unexpected certificates issued for your domains; TLS fingerprint (JA3/JA4) anomalies suggesting an interception proxy; client-side certificate pinning failures; unexpected ARP/DNS behavior as described in those respective entries.",
    defence: "HSTS to prevent protocol downgrade to plaintext HTTP; strict certificate validation with no exceptions for self-signed certs in production clients; certificate pinning for high-value mobile/API clients; mutual TLS where the threat model warrants it; user education against joining untrusted Wi-Fi networks for sensitive activity.",
    related: ["arp-spoofing", "dns-spoofing", "tls-ssl"],
    references: [{ label: "RFC 6797: HTTP Strict Transport Security" }],
  },
  {
    slug: "ddos",
    title: "Distributed denial of service (DDoS)",
    category: "network",
    summary: "Traffic or requests from many sources overwhelm a target's capacity to serve legitimate users.",
    what: "DDoS attacks exhaust a target's bandwidth, connection state, or application capacity using traffic distributed across many sources (often a botnet), making the service slow or entirely unavailable to legitimate users. Volumetric attacks saturate bandwidth; protocol attacks exhaust connection-state tables (SYN floods); application-layer attacks exhaust server resources with seemingly valid but expensive requests.",
    why: "Availability is one of the three pillars of security (confidentiality, integrity, availability) — a sustained DDoS can cause direct revenue loss, reputational damage, and is sometimes used as a smokescreen to distract defenders from a simultaneous intrusion.",
    how: "Volumetric: reflection/amplification via protocols that return a much larger response than the spoofed-source request (DNS, NTP, memcached). Protocol: SYN floods that exhaust a server's half-open connection table. Application-layer: repeated requests to expensive endpoints (search, login, report generation) that look legitimate individually.",
    detection: "Traffic volume and connection-rate anomalies against a baseline; a sudden concentration of traffic from a specific ASN/geography or via known amplification ports (53, 123, 11211); application metrics showing latency degradation under otherwise-normal-looking request patterns.",
    defence: "Upstream scrubbing/CDN capacity to absorb volumetric attacks before they reach origin infrastructure; SYN cookies to survive SYN floods without exhausting state; rate limiting and CAPTCHA challenges on expensive application endpoints; disabling or rate-limiting UDP-based amplification-prone services facing the internet; a tested incident response runbook, since DDoS mitigation is time-sensitive.",
    related: ["botnets"],
    references: [{ label: "RFC 4732: Internet Denial-of-Service Considerations" }],
  },
  {
    slug: "ransomware",
    title: "Ransomware",
    category: "malware",
    summary: "Malware that encrypts victim data and demands payment for the decryption key.",
    what: "Ransomware encrypts files (and, in modern 'double extortion' variants, first exfiltrates a copy) using strong symmetric encryption with a key the attacker controls, then demands payment — usually in cryptocurrency — for recovery, and separately threatens to leak the stolen data if payment isn't made.",
    why: "Ransomware can halt an entire organization's operations within hours, and modern strains specifically target and encrypt backups first to remove the easy recovery path, making it one of the most operationally disruptive and financially damaging threat categories.",
    how: "Initial access typically via phishing, exposed RDP with weak credentials, or exploitation of an unpatched internet-facing service; the operator then moves laterally, escalates privileges, disables/deletes backups and security tooling, exfiltrates data, and finally deploys the encryption payload broadly, often timed for off-hours.",
    detection: "Mass file-rename/modification events in a short window (file-integrity monitoring, EDR); shadow-copy or backup-deletion commands (vssadmin, wbadmin) in process logs; unusual outbound data transfer preceding encryption (the exfiltration stage); known ransomware-associated process names or C2 traffic via threat intelligence feeds.",
    defence: "Immutable, offline/air-gapped backups tested for restorability; network segmentation to slow lateral movement; least-privilege and no standing domain admin sessions; EDR with behavioral (not just signature) detection for mass encryption behavior; a tested incident response and communications plan, since the decision not to pay must be made calmly, not during the incident.",
    related: ["rootkits", "supply-chain-attacks"],
    references: [{ label: "MITRE ATT&CK T1486: Data Encrypted for Impact" }],
  },
  {
    slug: "rootkits",
    title: "Rootkits",
    category: "malware",
    summary: "Malware designed primarily to hide its own presence and that of other malicious activity.",
    what: "A rootkit's defining trait isn't its payload but its concealment mechanism — it hooks or patches OS interfaces (user-mode API hooking, kernel-mode driver, or below the OS entirely with a bootkit/firmware implant) so that processes, files, network connections, or registry keys it controls simply don't appear to standard system tools.",
    why: "A well-implemented rootkit defeats the normal signal an administrator would rely on (ps, netstat, Task Manager all lying), which is why detection increasingly relies on tools that don't trust the compromised OS's own reporting.",
    how: "User-mode rootkits hook API calls (e.g. intercepting directory-listing functions to hide a file). Kernel-mode rootkits install a malicious driver with the privilege to alter kernel data structures directly (DKOM — direct kernel object manipulation). Firmware/bootkit rootkits persist below the OS in the bootloader or UEFI, surviving a full OS reinstall.",
    detection: "Offline/out-of-band analysis that doesn't trust the live OS (booting from external media, memory forensics with tools like Volatility that parse raw memory structures rather than calling OS APIs); cross-view detection (comparing what the OS API reports versus a raw disk/memory scan and flagging discrepancies); Secure Boot and TPM-based attestation to detect firmware tampering.",
    defence: "Secure Boot with a measured boot chain (TPM) to detect firmware/bootkit tampering before the OS loads; kernel-mode code signing enforcement (Driver Signature Enforcement) to block unsigned kernel drivers; minimizing standing admin/root privilege, since kernel-mode installation requires it; rapid reimaging from known-good media as the reliable remediation once a rootkit is confirmed, rather than attempting in-place removal.",
    related: ["ransomware", "supply-chain-attacks"],
    references: [{ label: "MITRE ATT&CK T1014: Rootkit" }],
  },
  {
    slug: "botnets",
    title: "Botnets",
    category: "malware",
    summary: "A network of compromised devices under an attacker's remote command-and-control.",
    what: "A botnet is a collection of infected hosts (servers, PCs, or increasingly IoT devices with weak default credentials) that check in to a command-and-control (C2) infrastructure and execute whatever commands the operator issues — commonly DDoS, credential stuffing, spam, or acting as an anonymizing proxy layer for other attacks.",
    why: "Botnets provide an attacker with scale and attribution distance they couldn't achieve from their own infrastructure alone — thousands of source IPs make both a DDoS and a credential-stuffing campaign vastly harder to block or trace by IP alone.",
    how: "Devices are recruited via phishing, exploitation of unpatched services, or (heavily for IoT) simply trying default/weak credentials over SSH/Telnet; once infected, the bot connects to C2 (historically IRC, now more often HTTP/HTTPS or peer-to-peer/DGA-based fallback channels) and awaits instructions.",
    detection: "Beaconing traffic patterns to a C2 host at regular intervals (an anomaly this platform's own PCAP beaconing detector specifically looks for); DNS queries to algorithmically generated domains (DGA); a device suddenly participating in outbound scanning or flood traffic it has no legitimate reason to generate.",
    defence: "Change default credentials on every internet-facing device, especially IoT; keep firmware/OS patched to close the exploitation vector botnets rely on for growth; egress filtering so infected internal hosts can't freely reach arbitrary C2 destinations; network monitoring for beaconing and DGA-pattern DNS traffic.",
    related: ["ddos", "ransomware"],
    references: [{ label: "MITRE ATT&CK T1583.005: Acquire Infrastructure — Botnet" }],
  },
  {
    slug: "phishing",
    title: "Phishing",
    category: "identity",
    summary: "Deceptive communication designed to trick a target into revealing credentials or running malware.",
    what: "Phishing uses a message (email, SMS/'smishing', voice/'vishing', or a chat platform) that impersonates a trusted sender to trick the recipient into clicking a malicious link, entering credentials into a fake login page, or opening a malicious attachment. Spear phishing targets a specific individual with tailored context; whaling targets executives specifically.",
    why: "Phishing remains the most common initial-access vector for both opportunistic and targeted intrusions because it attacks the human element directly, sidestepping technical controls entirely — no vulnerability needs to exist in the target's software for it to work.",
    how: "The attacker researches the target enough to make the pretext credible (a fake invoice, a fake IT password-reset notice, a fake shared document), sends it via a spoofed or lookalike sender identity, and drives the victim to either a credential-harvesting page that visually mimics a real login screen or a malicious attachment/macro.",
    detection: "Email authentication failures (SPF/DKIM/DMARC) on inbound mail; user-reported suspicious emails correlated across the organization; sandboxed attachment/URL detonation catching malicious payloads before delivery; anomalous login patterns immediately following a phishing campaign (impossible travel, new device).",
    defence: "SPF, DKIM, and DMARC enforced (with a reject/quarantine policy, not just monitoring) to make sender spoofing harder; phishing-resistant multi-factor authentication (FIDO2/hardware keys, not SMS OTP) so a stolen password alone isn't enough; regular, realistic user training with simulated phishing; email gateway filtering with attachment/URL sandboxing.",
    related: ["credential-stuffing", "pass-the-hash"],
    references: [{ label: "MITRE ATT&CK T1566: Phishing" }],
  },
  {
    slug: "credential-stuffing",
    title: "Credential stuffing",
    category: "identity",
    summary: "Attackers replay username/password pairs leaked from one breach against other services.",
    what: "Credential stuffing automates login attempts using large lists of username/password pairs previously exposed in unrelated data breaches, relying on the widespread practice of password reuse across services to succeed even without any vulnerability in the targeted application itself.",
    why: "Because it exploits reused credentials rather than a flaw in the target, credential stuffing succeeds against otherwise well-secured applications purely on user behavior — and at scale, even a very low success rate yields a large absolute number of compromised accounts.",
    how: "The attacker acquires a breach corpus (widely traded, not fabricated by them), then runs automated login attempts against the target — often distributed across a botnet or a residential-proxy pool specifically to evade IP-based rate limiting and blocklists.",
    detection: "Login endpoint logs showing a high volume of attempts with low success rate, distributed across many source IPs but reusing the same credential-pair list ordering; a spike in 'password incorrect' events correlated with recent public breach disclosures; device/behavioral fingerprint anomalies for successful logins.",
    defence: "Multi-factor authentication as the strongest single mitigation, since a leaked password alone stops being sufficient; rate limiting and progressive delays per account and per IP/device; checking new and changed passwords against known-breached-password lists (e.g. via k-anonymity range queries) at signup/change time; device fingerprinting and risk-based/adaptive authentication.",
    related: ["phishing", "pass-the-hash"],
    references: [{ label: "MITRE ATT&CK T1110.004: Credential Stuffing" }],
  },
  {
    slug: "kerberoasting",
    title: "Kerberoasting",
    category: "identity",
    summary: "Requesting Kerberos service tickets to crack the service account password offline.",
    what: "In Active Directory, any authenticated user can request a Kerberos service ticket (TGS) for any service principal name (SPN) — that ticket is encrypted with a hash derived from the service account's password. Kerberoasting requests these tickets for all SPNs of interest, then attempts to crack the password hash offline, entirely outside the domain controller's visibility once the ticket has been captured.",
    why: "Service accounts frequently have old, weak, or never-rotated passwords (since a password change often breaks the service until manually reconfigured) and often hold elevated privileges — making them an efficient path from an ordinary authenticated user to a high-privilege account.",
    how: "The attacker enumerates SPNs in the domain, requests a TGS for each using their own low-privilege authenticated session (a completely legitimate-looking Kerberos operation), extracts the encrypted portion of each ticket, and attempts to crack it offline against the service account's password hash.",
    detection: "Domain controller logs (Event ID 4769) showing a single account requesting TGS tickets for an unusually large number of SPNs in a short window, especially using the weaker RC4 encryption type when AES is available.",
    defence: "Long, random passwords (25+ characters) for service accounts, or Group Managed Service Accounts (gMSA) with automatic rotation that make offline cracking infeasible; AES-only Kerberos encryption enforced domain-wide, removing the weaker RC4 option roastable tickets rely on; least privilege for service accounts so a cracked one isn't automatically high-value.",
    related: ["pass-the-hash", "phishing"],
    references: [{ label: "MITRE ATT&CK T1558.003: Kerberoasting" }],
  },
  {
    slug: "pass-the-hash",
    title: "Pass-the-hash",
    category: "identity",
    summary: "An attacker authenticates using a captured password hash directly, without ever knowing the plaintext.",
    what: "Windows NTLM authentication can be completed using the NTLM hash of a password rather than the plaintext itself. If an attacker obtains a hash — from memory (LSASS), a compromised machine's SAM database, or a network capture — they can authenticate to other systems that accept that hash, without ever cracking it.",
    why: "This breaks the usual assumption that stealing a hash 'only' risks offline cracking — a hash alone is often sufficient credential material on its own, and because it's typically obtained from memory of an already-compromised host, it enables fast lateral movement to every other machine where that credential is valid (often local admin accounts shared across a fleet).",
    how: "The attacker dumps credential material from a compromised host's memory (commonly via tools that read LSASS process memory) or the local SAM database, then uses that hash directly in an NTLM authentication exchange against another host, rather than attempting to crack it to plaintext first.",
    defence: "Unique local administrator passwords per machine (e.g. via Microsoft LAPS) so one dumped hash doesn't grant admin everywhere; Credential Guard to isolate LSASS secrets from the OS itself using virtualization-based security; restricting NTLM in favor of Kerberos where possible; tiered administration so high-privilege credentials never touch lower-tier, more-exposed workstations.",
    detection: "Authentication logs showing NTLM logons where Kerberos would be expected (Event ID 4624 with LogonType 3 and NTLM package); a single credential authenticating to an unusually large number of hosts in a short window; EDR alerts on LSASS memory access by non-standard processes.",
    related: ["kerberoasting", "credential-stuffing"],
    references: [{ label: "MITRE ATT&CK T1550.002: Pass the Hash" }],
  },
  {
    slug: "cloud-misconfiguration",
    title: "Cloud misconfiguration",
    category: "cloud",
    summary: "Insecure default or operator-set settings expose cloud resources beyond their intended audience.",
    what: "Cloud misconfiguration covers a broad set of operator errors — a storage bucket left publicly readable/writable, an overly permissive IAM policy (wildcard actions/resources), a security group open to 0.0.0.0/0 on a sensitive port, or unencrypted data at rest — that expose resources or data without any code vulnerability being involved at all.",
    why: "Misconfiguration is consistently one of the leading causes of cloud data breaches precisely because it requires no exploit — a publicly readable storage bucket is discoverable by simple enumeration, not by a targeted attack, and shared-responsibility confusion (assuming the provider secures what the customer must configure) makes it common.",
    how: "An attacker (or automated scanner) enumerates common cloud storage naming patterns or discovers a bucket/endpoint via passive reconnaissance (certificate transparency logs, JS bundle references, GitHub commits), then simply requests the resource directly — no authentication bypass needed if the resource is misconfigured as public.",
    detection: "Cloud Security Posture Management (CSPM) tooling continuously scanning for public storage, open security groups, and overly permissive IAM policies; cloud provider access logs showing anonymous/unauthenticated reads on resources that should require auth; certificate transparency and passive DNS monitoring for unexpected newly-public endpoints.",
    defence: "Default-deny storage and network access, opting in explicitly to public exposure only where truly required; least-privilege IAM policies scoped to specific resources and actions, not wildcards; infrastructure-as-code with policy-as-code checks (e.g. blocking public buckets) enforced in CI before deployment; encryption at rest by default and secrets never stored in code or environment-visible plaintext.",
    related: ["ssrf", "supply-chain-attacks", "container-escape"],
    references: [{ label: "CWE-668: Exposure of Resource to Wrong Sphere" }],
  },
  {
    slug: "container-escape",
    title: "Container escape",
    category: "cloud",
    summary: "A process breaks out of its container's isolation to access the underlying host.",
    what: "Containers share the host kernel and rely on namespaces, cgroups, and (ideally) additional sandboxing to isolate workloads — a container escape is any technique that breaks out of that isolation to read, write, or execute on the host itself or on other containers sharing it.",
    why: "A single-host compromise inside one container can turn into full-host compromise (and from there, every other workload scheduled on that host) if the escape succeeds, defeating the entire premise of using containers to isolate untrusted or multi-tenant workloads.",
    how: "Common vectors: a container run with excessive privileges (--privileged, or specific dangerous capabilities like CAP_SYS_ADMIN) that grants direct access to host devices or the ability to remount the host filesystem; a mounted Docker socket inside the container, which is effectively equivalent to host root; a kernel vulnerability exploitable from within the container's namespace since the kernel itself is shared.",
    detection: "Runtime security tooling (eBPF-based sensors) alerting on container processes attempting host-namespace operations, unexpected mount syscalls, or access to the Docker/containerd socket; anomalous capability usage compared to the container's declared profile.",
    defence: "Run containers as non-root with the minimum capability set required (drop ALL, add back only what's needed) rather than --privileged; never mount the container runtime's control socket into a workload container; use a stronger isolation boundary (gVisor, Kata Containers/microVMs) for genuinely untrusted or multi-tenant workloads; keep the host kernel patched, since container isolation is only as strong as the shared kernel underneath it.",
    related: ["cloud-misconfiguration", "supply-chain-attacks"],
    references: [{ label: "MITRE ATT&CK T1611: Escape to Host" }],
  },
  {
    slug: "supply-chain-attacks",
    title: "Software supply chain attacks",
    category: "cloud",
    summary: "Compromising a trusted upstream component to reach every downstream consumer of it.",
    what: "Rather than attacking a target directly, a supply chain attack compromises something the target trusts and pulls in automatically — an open-source package, a build tool, a CI/CD pipeline, or a software update mechanism — so the malicious code is delivered with the target's own consent, via a channel that isn't scrutinized the way direct network access would be.",
    why: "A single compromised widely-used dependency or build system can reach thousands of downstream organizations simultaneously, and because the code arrives through an ostensibly trusted update or install process, it frequently bypasses the security review normally applied to unsolicited code.",
    how: "Dependency-level: typosquatting a popular package name, or compromising a maintainer's account/credentials to publish a malicious version of a legitimate package. Build-level: compromising CI/CD infrastructure to inject malicious code during the build step, so the source repository itself can look clean. Update-level: compromising a vendor's software update/signing infrastructure to push malicious updates as if from the vendor.",
    detection: "Software Bill of Materials (SBOM) diffing to spot unexpected new or changed dependencies between releases; dependency vulnerability scanning against known-malicious package databases (OSV and equivalents); build reproducibility checks; unusual network activity from build/CI infrastructure.",
    defence: "Pin exact dependency versions and verify checksums/signatures rather than trusting a mutable version range; generate and review an SBOM for every release; require signed commits and protected, reviewed CI/CD pipeline changes; least-privilege for CI systems so a compromised pipeline step can't reach unrelated secrets; vet new dependencies before adoption, favoring actively-maintained ones with a track record.",
    related: ["ransomware", "cloud-misconfiguration", "container-escape"],
    references: [{ label: "MITRE ATT&CK T1195: Supply Chain Compromise" }, { label: "OWASP Top 10 A08:2021 — Software and Data Integrity Failures" }],
  },
  {
    slug: "siem",
    title: "SIEM (Security Information and Event Management)",
    category: "detection",
    summary: "Centralized collection, correlation, and alerting across an organization's log sources.",
    what: "A SIEM ingests logs and events from across the environment — endpoints, network devices, cloud services, applications — normalizes them into a common schema, and applies correlation rules or analytics to surface activity that no single log source would reveal in isolation.",
    why: "Individual log sources are typically reviewed in isolation, if at all, and many attack patterns (a login from a new country immediately followed by mass file access) only become visible when events from different sources are correlated together in near-real time.",
    how: "Not an attack technique — a defensive control. Log sources forward events (via agents, syslog, or API pull) to the SIEM, which parses and normalizes them, applies detection rules/analytics (from simple threshold rules to behavioral baselining), and raises alerts routed to an analyst or SOAR playbook for triage.",
    detection: "N/A — this is itself the detection layer other entries in this encyclopedia describe alerting through.",
    defence: "Not applicable in the usual sense — operational guidance instead: tune correlation rules against your actual environment to control false-positive volume; ensure log sources cover the full attack surface (endpoint, network, identity, cloud) rather than concentrating only on what's easiest to ingest; retain logs long enough to support investigation of slow-burn intrusions; pair the SIEM with a documented, exercised incident response process, since alerts without a response plan don't reduce risk.",
    related: ["edr", "threat-intelligence", "incident-response-lifecycle"],
    references: [{ label: "NIST SP 800-92: Guide to Computer Security Log Management" }],
  },
  {
    slug: "edr",
    title: "EDR (Endpoint Detection and Response)",
    category: "detection",
    summary: "Continuous endpoint telemetry and behavioral analysis, with the ability to respond in place.",
    what: "EDR agents run on endpoints (servers, workstations) recording process creation, file, registry, and network activity in detail, applying behavioral detection (not just signature matching) to that telemetry, and giving responders the ability to isolate a host, kill a process, or collect forensic artifacts remotely.",
    why: "Signature-based antivirus alone misses novel or living-off-the-land techniques that use legitimate system tools maliciously; EDR's behavioral approach and rich telemetry let defenders detect and investigate activity that never matches a known malware signature.",
    how: "Not an attack technique — a defensive control. The agent hooks OS-level events (process creation, module loads, network connections) and streams them to a central platform, which applies behavioral detections and retains the telemetry for retrospective hunting once new threat intelligence emerges.",
    detection: "N/A — this is itself a detection layer.",
    defence: "Deploy on all endpoints including servers, not just user workstations, since attackers specifically target the gaps in coverage; tune detections to your environment to keep alert volume actionable; ensure responders have practiced the isolation/response workflow before a real incident, since speed of containment directly limits blast radius; retain telemetry long enough to support hunting against newly-disclosed threat intelligence.",
    related: ["siem", "incident-response-lifecycle"],
    references: [{ label: "MITRE ATT&CK: Data Sources — Process, Network Traffic, File" }],
  },
  {
    slug: "threat-intelligence",
    title: "Threat intelligence & IOCs",
    category: "detection",
    summary: "Structured knowledge about threats — indicators, TTPs, and context — used to inform defense.",
    what: "Threat intelligence ranges from tactical indicators of compromise (IOCs — malicious hashes, IPs, domains) to operational understanding of adversary tactics, techniques, and procedures (TTPs, as catalogued by MITRE ATT&CK), to strategic intelligence about which threat actors target an organization's sector and why.",
    why: "Raw indicators alone go stale quickly (an IP or domain can be abandoned within days), but understanding TTPs lets defenses target the behaviors an adversary must exhibit to succeed — which are far more durable than any single indicator — while strategic context helps prioritize defensive investment toward the threats actually relevant to the organization.",
    how: "Not an attack technique — intelligence about attacks. Sources include commercial and open-source feeds, information-sharing communities (ISACs), malware sandbox detonation reports, and an organization's own incident findings, ideally structured in an interoperable format (STIX/TAXII) so it can feed directly into detection tooling.",
    detection: "N/A — threat intelligence feeds and informs detection elsewhere (SIEM correlation rules, EDR watchlists) rather than being a detection mechanism itself.",
    defence: "Prioritize TTP-level detections over indicator-only matching, since indicators expire fast and TTPs don't; validate feed quality — false positives and stale/decommissioned indicators actively erode analyst trust in the intelligence program; tie intelligence explicitly back to your own environment's exposure rather than consuming feeds generically; feed confirmed findings back into the detection stack (SIEM/EDR) as a closed loop.",
    related: ["siem", "edr", "sigma-yara"],
    references: [{ label: "MITRE ATT&CK" }, { label: "OASIS STIX/TAXII" }],
  },
  {
    slug: "sigma-yara",
    title: "Sigma & YARA detection rules",
    category: "detection",
    summary: "Portable, human-readable rule formats for detecting log patterns (Sigma) and files/memory (YARA).",
    what: "Sigma is a generic, YAML-based rule format for log-based detection — a single Sigma rule compiles to native query syntax for many SIEM backends, avoiding rewriting the same detection logic per platform. YARA describes patterns (strings, byte sequences, and boolean logic over them) for identifying malware families or specific files/memory regions, independent of any single log format.",
    why: "Without a shared format, every detection has to be hand-translated for each platform, and every YARA-equivalent pattern has to be re-implemented per scanning tool — both slow down detection-sharing across the community and across an organization's own tool estate.",
    how: "Not an attack technique — detection engineering. A Sigma rule declares a log source, a selection of field/value conditions, and a boolean condition combining them; a YARA rule declares string/byte patterns and a condition over how many/which must match. Crucially, a detection only means something has actually been evaluated against real data — a rule that was never run against an appropriate log source or sample proves nothing.",
    detection: "N/A — these are themselves detection-authoring formats, evaluated by this platform's own local YARA engine and Sigma converter/evaluator (see the Detection lab) against files and log data you provide.",
    defence: "Write detections at the TTP level where possible (matching the technique, not one specific tool's default output) so they survive an adversary changing tooling; version-control rules and track their provenance/false-positive history; validate every new rule against both malicious and benign samples before deploying it, to establish real precision rather than assumed coverage.",
    related: ["threat-intelligence", "edr"],
    references: [{ label: "SigmaHQ specification" }, { label: "YARA documentation" }],
  },
  {
    slug: "incident-response-lifecycle",
    title: "Incident response lifecycle",
    category: "detection",
    summary: "The structured process from preparation through detection, containment, eradication, and recovery.",
    what: "Incident response follows a recognized lifecycle — commonly Preparation, Detection & Analysis, Containment, Eradication, Recovery, and Post-Incident Activity (lessons learned) — that turns an ad hoc scramble into a repeatable, defensible process, and ensures evidence handling supports both technical remediation and any later legal or regulatory need.",
    why: "Skipping preparation means discovering during a real incident that logs aren't retained long enough, responders lack access, or there's no communication plan; skipping containment discipline (e.g. tipping off an attacker by remediating visibly before understanding full scope) can cause an adversary to accelerate destructive actions.",
    how: "Not an attack technique — response process. Preparation builds the tooling, access, and playbooks beforehand; Detection & Analysis scopes what actually happened; Containment isolates affected systems (short-term) without necessarily eradicating yet, to preserve evidence and understand full scope; Eradication removes the actual foothold (accounts, malware, persistence); Recovery restores systems to trusted operation with monitoring for reinfection; Post-Incident Activity captures lessons learned and updates defenses.",
    detection: "N/A — this is the response process that follows detection, not a detection mechanism itself.",
    defence: "Maintain a written, exercised incident response plan with clear roles (technical lead, communications, legal) decided before an incident, not during one; ensure log retention and access are sufficient to actually scope an incident when it happens; practice via tabletop exercises regularly, since the plan's first real test should not be a live incident; always complete the post-incident lessons-learned step, since it's the step most often skipped under time pressure and the one that most improves next time.",
    related: ["siem", "edr", "chain-of-custody"],
    references: [{ label: "NIST SP 800-61r2: Computer Security Incident Handling Guide" }],
  },
  {
    slug: "chain-of-custody",
    title: "Digital forensics & chain of custody",
    category: "detection",
    summary: "Documenting evidence handling so its integrity and origin can be defended later, including in court.",
    what: "Chain of custody is the documented, unbroken record of who collected a piece of evidence, when, how, and who has had access to or handled it since — combined with forensic integrity practices (write-blocking, cryptographic hashing of acquired images) that let a later party verify the evidence hasn't been altered since collection.",
    why: "Without documented chain of custody and provable integrity, evidence — even if technically accurate — can be challenged or excluded in legal proceedings, and internally, undocumented handling makes it impossible to be confident an artifact wasn't altered (intentionally or accidentally) during an investigation.",
    how: "Not an attack technique — evidentiary discipline. Acquire data using write-blocking hardware/software so the source is never modified; hash the acquired image immediately (and re-verify the hash before any analysis) so integrity is provable; log every access, transfer, and analysis step with timestamps and identities; store evidence in a controlled location with access logging.",
    detection: "N/A — this is a forensic/evidentiary practice, not a detection mechanism.",
    defence: "Establish forensic acquisition procedures and tooling before they're needed under incident pressure; hash-verify at every handoff, not just at initial acquisition; keep the chain-of-custody log as rigorous for an internal-only investigation as one that might become legal evidence, since that determination isn't always clear at the start.",
    related: ["incident-response-lifecycle"],
    references: [{ label: "NIST SP 800-86: Guide to Integrating Forensic Techniques into Incident Response" }],
  },
  {
    slug: "tls-ssl",
    title: "TLS / SSL",
    category: "crypto",
    summary: "The protocol that provides confidentiality, integrity, and authentication for network communication.",
    what: "TLS (the modern successor to the deprecated SSL) establishes an authenticated, encrypted channel between two parties. A handshake negotiates the protocol version and cipher suite, authenticates the server (and optionally the client) via an X.509 certificate chain rooted in a trusted Certificate Authority, and derives session keys — after which application data is encrypted and integrity-protected.",
    why: "TLS is the baseline that makes the modern web's threat model (routinely untrusted networks, public Wi-Fi, on-path attackers) survivable — without it, every plaintext protocol is trivially readable and tamperable by anyone positioned on the path, as ARP/DNS spoofing and MITM entries in this encyclopedia describe.",
    how: "Not an attack technique — the protocol itself. Weaknesses arise from misconfiguration or implementation flaws rather than the protocol's core design in modern versions: accepting deprecated versions (SSLv3, TLS 1.0/1.1) or weak cipher suites, failing to validate the certificate chain or hostname, or using a CA/implementation with a known vulnerability.",
    detection: "TLS fingerprinting (JA3/JA4) to identify anomalous or interception-proxy client/server implementations; certificate transparency log monitoring for unexpected certificates issued for your domains; scanning for deprecated protocol versions or weak cipher suites still enabled on your own endpoints.",
    defence: "TLS 1.2 minimum, TLS 1.3 preferred, with deprecated versions and weak ciphers disabled; strict certificate and hostname validation with no exceptions in production code paths; HSTS to prevent downgrade to plaintext HTTP; automated certificate renewal to avoid expiry-driven outages that train users to click through warnings; regular scanning of your own TLS configuration against current best-practice baselines.",
    related: ["man-in-the-middle", "password-hashing"],
    references: [{ label: "RFC 8446: TLS 1.3" }],
  },
  {
    slug: "password-hashing",
    title: "Password hashing & storage",
    category: "crypto",
    summary: "How credentials should be stored so a database breach doesn't directly expose usable passwords.",
    what: "Passwords must never be stored in plaintext or with a fast general-purpose hash (MD5, SHA-1, SHA-256 alone) — they should be run through a purpose-built, deliberately slow, memory-hard password hashing function (Argon2id, scrypt, or bcrypt) with a unique random salt per password, so that even a full database compromise doesn't yield usable credentials without extremely costly offline computation per password.",
    why: "A fast hash lets an attacker with GPU/ASIC resources test billions of candidate passwords per second offline once a hash database leaks; a slow, memory-hard function with proper parameters reduces that to a small fraction of that rate, making large-scale offline cracking economically infeasible even against a full breach.",
    how: "Not an attack technique — storage guidance. The corresponding attack (offline cracking) applies a wordlist, rules-based mutations, or brute force against a stolen hash database, succeeding fastest against unsalted hashes (rainbow tables), fast general-purpose hashes, and weak/reused passwords.",
    detection: "N/A for the defensive practice itself; the corresponding attack is detected via the credential-stuffing entry's guidance once cracked credentials are reused against live services.",
    defence: "Argon2id (or bcrypt/scrypt where Argon2 isn't available) with parameters tuned to your acceptable latency budget, never a fast general-purpose hash; a unique random salt per password (handled automatically by all of the above); a server-side pepper (a secret key mixed into every hash, stored outside the database) as additional defense in depth; enforce a minimum password length over complexity rules, and check new passwords against known-breached lists.",
    related: ["tls-ssl", "credential-stuffing"],
    references: [{ label: "RFC 9106: Argon2 Memory-Hard Function" }, { label: "OWASP Password Storage Cheat Sheet" }],
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function relatedArticles(a: Article): Article[] {
  return a.related.map((slug) => getArticle(slug)).filter((x): x is Article => !!x);
}

export function searchArticles(query: string, category?: ArticleCategory): Article[] {
  const q = query.trim().toLowerCase();
  return ARTICLES.filter((a) => {
    if (category && a.category !== category) return false;
    if (!q) return true;
    return a.title.toLowerCase().includes(q) || a.summary.toLowerCase().includes(q) || a.what.toLowerCase().includes(q);
  });
}
